### ISSUE TITLE
Problem with potion installation

### ISSUE THREAD

**Issue by vanqyard** [perl11/potion#100]
I am having a problem with installing potion (although I think I have installed all dependencies). There are two different cases:
1) make
<code>

[ successful tests ]
.............
OK (13 tests)

running GC tests
......
OK (6 tests)

running bin/potion VM tests
.................................................................................
*\* test/tables/filter.pn: expected <(bread, mayo)>, but got <(cheese, mayo)>
.............
running bin/potion compiler tests
.................................................................................
*\* test/tables/filter.pn: expected <(bread, mayo)>, but got <(mayo, bread)>
.............
running bin/potion JIT tests
.................................................................................
*\* test/tables/filter.pn: expected <(bread, mayo)>, but got <(cheese, mayo)>
.............
3 FAILS (282 tests)
make: **\* [test] Błąd 1
</code>

1) make JIT=0
I have successful compilation and tests but after make install (had to translate some errors from my language):
<code>
[ ... ]
cp: can't execute stat on „doc/_.html”: No such file or directory
dist.mak:36: commands for object 'pkg/potion-0.3.1300-x86_64-linux-gnu.tar.gz' have not succeeded
make[1]: [pkg/potion-0.3.1300-x86_64-linux-gnu.tar.gz] Failure 1 (ignored)
[ ... ]
make[1]: *_\* No rules to build object 'bin/potion-s', needed by 'pkg/potion-0.3.1300-x86_64-linux-gnu-devel.tar.gz'. Stop.
[ ... ]
</code>
# 

When I build with 
$ make bin/potion-s 
the problem with broken tests still occurs

**Comment by rurban** [comment]
ad 1) yes. the tests in master still fail due to a missing sort in the new tests.
ad 2) yes, potion-s and the doc targets for make install are not yet stable enough.

**Comment by benknoble** [comment]
@rurban I have the `bin/potion-s` problems on a `make install`; is there a fix?
