### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by jamespeace** [perl11/potion#102]
- Operating system/version: ubuntu 16.04.4
- gcc: 5.4.0

Should I use clang rather than gcc to build potion on Ubuntu?

$make
`
CC lib/database.opic
lib/database.c:8:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.
Makefile:233: recipe for target 'lib/database.opic' failed
make: *** [lib/database.opic] Error 1
`

**Comment by clouduan** [comment]
+1 for this problem :neckbeard:

**Comment by robotii** [comment]
I think you will need to install the sqlite development headers.

sudo apt-get install libsqlite3-dev

**Comment by rurban** [comment]
Yes, probing for external dependencies should be added. It's a very simple and pure make script only.
