### ISSUE TITLE
callset on nil segfaults

### ISSUE THREAD

**Issue by robotii** [perl11/potion#84]
The following code causes a segfault under both the bytecode and jit compiler

```
nil() = 5
```

basically, there is a NULL pointer for the first child of the AST_MSG that is used to store the message name. Probably this should be corrected by falling over in a slightly nicer way.

Error is right after the line
``` c
if (lhs->part == AST_MSG || lhs->part == AST_QUERY) {
```

in compile.c

**Comment by rurban** [comment]
Thanks. That makes a nice compile time error. I choose
```
bin/potion -e 'nil() = 0'
** Syntax error: Call empty message at "nil", line 1
```

**Comment by vendethiel** [comment]
oooh, that's a nice improvement! :+1:
