### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by wollmers** [perl11/potion#85]
Installing from a release fails when accessing the .git for unneeded POTION_COMMIT and POTION_REV updates, which need to be skipped for releases.

    https://github.com/perl11/potion/archive/potion-0.3.tar.gz

    helmut@helmuts-air:~/github/potion-potion-0.3$ make
    Makefile:13: config.inc: No such file or directory
    fatal: Not a git repository (or any of the parent directories): .git
    config.mak:276: config.inc: No such file or directory
    fatal: Not a git repository (or any of the parent directories): .git

**Comment by rurban** [comment]
yes, this is a known problem. I thought we already had a ticket for this...
