### ISSUE TITLE
compile: unknown builtin '__builtin_saddl_overflow'

### ISSUE THREAD

**Issue by wollmers** [perl11/potion#86]
OSX 10.9.5
Xcode 5.0.2

    helmut@helmuts-air:~/github/potion$ git submodule update --init

[OK]

```
    helmut@helmuts-air:~/github/potion$ make
    Makefile:13: config.inc: No such file or directory
    config.mak:276: config.inc: No such file or directory
    [...]
   CC core/vm.opic
    core/vm.c:746:17: error: use of unknown builtin '__builtin_saddl_overflow'
          [-Wimplicit-function-declaration]
          CASE(ADD, PN_VM_MATH3(add, +, saddl))
                    ^
    core/vm.c:384:9: note: expanded from macro 'PN_VM_MATH3'
        if (__builtin_##ov##_overflow(PN_INT(reg[op.a]), PN_INT(reg[op.b]), ...
            ^
    <scratch space>:280:1: note: expanded from here
    __builtin_saddl_overflow
    ^
    core/vm.c:686:34: note: expanded from macro 'CASE'
    #define CASE(op, block) L(op): { block; } goto L_end;
                                     ^
    core/vm.c:747:17: error: use of unknown builtin '__builtin_ssubl_overflow'
          [-Wimplicit-function-declaration]
          CASE(SUB, PN_VM_MATH3(sub, -, ssubl))
                    ^
    core/vm.c:384:9: note: expanded from macro 'PN_VM_MATH3'
        if (__builtin_##ov##_overflow(PN_INT(reg[op.a]), PN_INT(reg[op.b]), ...
            ^
    <scratch space>:284:1: note: expanded from here
    __builtin_ssubl_overflow
    ^
    core/vm.c:686:34: note: expanded from macro 'CASE'
    #define CASE(op, block) L(op): { block; } goto L_end;
                                 ^
core/vm.c:747:17: note: did you mean '__builtin_saddl_overflow'?
core/vm.c:384:9: note: expanded from macro 'PN_VM_MATH3'
    if (__builtin_##ov##_overflow(PN_INT(reg[op.a]), PN_INT(reg[op.b]), ...
            ^
    <scratch space>:284:1: note: expanded from here
    __builtin_ssubl_overflow
    ^
    core/vm.c:686:34: note: expanded from macro 'CASE'
    #define CASE(op, block) L(op): { block; } goto L_end;
                                     ^
    core/vm.c:748:17: error: use of unknown builtin '__builtin_smull_overflow'
          [-Wimplicit-function-declaration]
          CASE(MULT,PN_VM_MATH3(mult, *, smull))
                    ^
    core/vm.c:384:9: note: expanded from macro 'PN_VM_MATH3'
        if (__builtin_##ov##_overflow(PN_INT(reg[op.a]), PN_INT(reg[op.b]), ...
            ^
    <scratch space>:284:1: note: expanded from here
    __builtin_smull_overflow
    ^
    core/vm.c:686:34: note: expanded from macro 'CASE'
    #define CASE(op, block) L(op): { block; } goto L_end;
                                     ^
    core/vm.c:748:17: note: did you mean '__builtin_ssubl_overflow'?
    core/vm.c:384:9: note: expanded from macro 'PN_VM_MATH3'
        if (__builtin_##ov##_overflow(PN_INT(reg[op.a]), PN_INT(reg[op.b]), ...
            ^
    <scratch space>:284:1: note: expanded from here
    __builtin_smull_overflow
    ^
    core/vm.c:686:34: note: expanded from macro 'CASE'
    #define CASE(op, block) L(op): { block; } goto L_end;
                                    ^
    3 errors generated.
    make: *** [core/vm.opic] Error 1
```

**Comment by rurban** [comment]
Oh, so apple bumped the clang version but did support the overflow builtins?
What is your __clang_minor__ version on this? 

I assumed 3.4 added this, as documented in http://llvm.org/releases/3.4/tools/clang/docs/LanguageExtensions.html#builtin-functions

**Comment by wollmers** [comment]
Now upgraded Xcode command line tools to 6.2, but the same compile errors. Didn't manage to upgrade Xcode, still 5.0.2. Seems you have Yosemite and Xcode 7.

    $ clang -dM -E -x c /dev/null | grep __clang_
    #define __clang__ 1
    #define __clang_major__ 5
    #define __clang_minor__ 0
    #define __clang_patchlevel__ 0
    #define __clang_version__ "5.0 (clang-500.2.79)"

Thx, your patch works, just throws warnings now:

      CC       src/unix/libuv_la-stream.lo
    src/unix/stream.c:1054:19: warning: variable length array folded to constant array as an extension
          [-Wpedantic]
      char cmsg_space[CMSG_SPACE(UV__CMSG_FD_SIZE)];
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/sys/socket.h:517:24: note: expanded from macro 'CMSG_SPACE'
    #define CMSG_SPACE(l)           (__DARWIN_ALIGN32(sizeof(struct cmsghdr)) + __DARWIN_ALIGN32(l))
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/unix/stream.c:1054:19: note: cast which performs the conversions of a reinterpret_cast is not allowed in
          a constant expression
    /usr/include/sys/socket.h:517:25: note: expanded from macro 'CMSG_SPACE'
    #define CMSG_SPACE(l)           (__DARWIN_ALIGN32(sizeof(struct cmsghdr)) + __DARWIN_ALIGN32(l))
                                     ^
    /usr/include/i386/_param.h:43:42: note: expanded from macro '__DARWIN_ALIGN32'
    #define       __DARWIN_ALIGN32(p)       ((__darwin_size_t)((char *)(__darwin_size_t)(p) + __DARWIN_AL...
                                             ^
    1 warning generated.

**Comment by wollmers** [comment]
I close this issue, hope you agree.

BTW: It's really, really fast.

**Comment by rurban** [comment]
Great so 7 is the right number then. Have to fix cperl now also
